### PR TITLE
PLF-8608: Define the fvh highlighter

### PR DESCRIPTION
**Pull request by hassenelkamel-exo**
In order to increase the performance of highlighting in Elastic-search, we apply another highlighter `fvh Fast Vector `highlighter to attachment.content which has a big size of content.

### CODE REVIEW

**Review by ahamdi — APPROVED** [review]
LGTM

**Comment by hbenali** [comment]
@ahamdi  Do you still need to work on this PR? Otherwise, please close this PR. Thank you!

**Comment by ahamdi** [comment]
@hbenali We worked on this issue and were waiting for the validation from ITOP team as they were the reporter of this problem. We do still wait for you to schedule th evalidation of the issue.

**Comment by hbenali** [comment]
@halaya Could you consider this, please? Thanks

**Pull request closed without merging**
