### PR TITLE
Add JQuery RSS plugin.

### PR DESCRIPTION
**Pull request by mdiha**
This RSS plugin is needed for parsing Rss feeds in CLV templates.

### CODE REVIEW

**Comment by ahamdi** [comment]
@mdiha Could you add a task for this PR?
what is the scope of this task?

**Comment by mdiha** [comment]
> @mdiha Could you add a task for this PR?
> what is the scope of this task?

Needed for client projects to make the added RSS Feeds template portable.

**Comment by ahamdi** [comment]
Did you add the CLV template for RSS feeds ?

**Comment by mdiha** [comment]
> Did you add the CLV template for RSS feeds ?

@ahamdi Not in the product

**Comment by ahamdi** [comment]
> > Did you add the CLV template for RSS feeds ?
> 
> @ahamdi Not in the product

Then no need to add Jquery RSS in the Product, unless it is used by some feature already in the product.

**Pull request closed without merging**
